name: linters
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  js-linter:
    name: Javascript linter (standard)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Init yarn
        run: yarn install
      - name: Run Standard
        run: yarn standard html/index.js
      - uses: crate-ci/typos@master
  css-linter:
    name: CSS linter (stylelint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Init yarn
        run: yarn install
      - name: Run stylelint
        run: yarn stylelint html/*.css
  html-linter:
    name: HTML linter (html5validator) 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            https://example.com/
            https://example.com/blog
          budgetPath: ./html/index.html # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage